-- Supabase SQL Schema for SiteShield AI Geofence Attendance Portal
-- Paste this script directly into your Supabase SQL Editor (found in the sidebar of your Supabase dashboard).

-- 1. Create Supervisors Table
create table if not exists supervisors (
  id text primary key,
  name text not null,
  "referenceFaceDescriptor" double precision[] null,
  "referenceImage" text null
);

-- 2. Create Users Table
create table if not exists users (
  username text primary key,
  name text not null,
  password text not null,
  role text not null check (role in ('admin', 'supervisor')),
  "supervisorId" text references supervisors(id) on delete set null
);

-- 3. Create Checkins Table
create table if not exists checkins (
  id bigint generated by default as identity primary key,
  "supervisorId" text references supervisors(id) on delete cascade,
  "supervisorName" text not null,
  timestamp bigint not null,
  latitude double precision not null,
  longitude double precision not null,
  image text not null,
  "locationName" text null,
  "similarityScore" double precision null,
  "faceMatchStatus" text not null check ("faceMatchStatus" in ('matched', 'mismatched', 'not_verified'))
);

-- 4. Disable Row Level Security (RLS) for testing ease
-- This allows our React Web app and the Flutter Mobile app to read/write directly
alter table supervisors disable row level security;
alter table users disable row level security;
alter table checkins disable row level security;
